### ISSUE TITLE
integrate language labels sparql query 

### ISSUE THREAD

**Issue by andrecastro0o** [DANS-KNAW/landscape-analysis-Getty-AAT#1]
@aapolimeno I have added the  [sparql/aat_subject_label.rq](sparql/aat_subject_label.rq) to query one of the subjects' ttl [sparql/aat_300123559.ttl](sparql/aat_300123559.ttl)

Perhaps you can integrate modify this query the Getty endpoing, and be able to query any term's label.

Also would be nice to integrate it into the notebook, so that Jetze can see. For the Python notebook, you will most likely need to use  [RDFlib](https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html)

Have fun. and should if you get stuck

**Comment by aapolimeno** [comment]
done, I included a cell that allows for the input of any subjectID and returns the corresponding labels.
